//! Phase 2.13.1: end-to-end synthetic Qwen-hybrid-mini integration test.
//!
//! Loads the fixture in `oracle/test_vectors/qwen_hybrid_mini/`
//! (generated by `oracle/synthetic_qwen_hybrid_mini.py`) via
//! `Model::load`, runs `forward_prefix` with the same prompt, and asserts
//! byte-equality with the numpy reference's saved outputs.
//!
//! What this proves:
//! 1. **Disk format round-trip for QwenStandard + QwenHybridSsm.** Both
//!    layer tags (3 and 4) round-trip through the canonical disk
//!    serializer. Manifest v2 (arch_tag + feature_flags) is encoded
//!    correctly on the Python side and parsed correctly on the Rust side.
//! 2. **Cross-impl forward parity.** The numpy reference's
//!    `forward_qwen_standard_layer` / `forward_qwen_hybrid_ssm_layer` /
//!    `ssm_forward` / `gated_attention_forward` produce byte-equal
//!    outputs to the Rust crate on a 4-token prompt run through 2 layers.
//! 3. **`comm_W` parity across architectures.** The Python comm_W
//!    computation (with `arch_tag="qwen35"`) matches the Rust crate's
//!    `compute_comm_w` for the same model.
//!
//! `cargo test -p ai-pow-vi --test oracle_qwen_hybrid_mini`

use std::path::{Path, PathBuf};

use ai_pow_vi::activations::{ActivationLayout, ActivationLog};
use ai_pow_vi::comm_w::compute_comm_w;
use ai_pow_vi::forward::forward_prefix;
use ai_pow_vi::layer::LayerContext;
use ai_pow_vi::model::Model;

fn vectors_dir() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .join("oracle")
        .join("test_vectors")
        .join("qwen_hybrid_mini")
}

fn read_i8(path: &Path) -> Vec<i8> {
    std::fs::read(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
        .into_iter()
        .map(|b| b as i8)
        .collect()
}

fn read_u32(path: &Path) -> Vec<u32> {
    let bytes = std::fs::read(path).unwrap();
    bytes
        .chunks_exact(4)
        .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn read_hex_32(path: &Path) -> [u8; 32] {
    let s = std::fs::read_to_string(path).unwrap();
    let s = s.trim();
    assert_eq!(s.len(), 64, "comm_w.hex must be 64 chars");
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
    }
    out
}

#[test]
#[ignore = "hybrid layout swapped to DeltaNet semantics; fixture uses stale Mamba dims. \
    Regenerate via NEXT_STEPS.md Path A."]
fn qwen_hybrid_mini_load_succeeds_with_recorded_comm_w() {
    let dir = vectors_dir();
    let expected = read_hex_32(&dir.join("comm_w.hex"));
    let model = Model::load(&dir, &expected).expect("Model::load failed");
    assert_eq!(compute_comm_w(&model), expected);
    // arch_tag must be "qwen35" padded to 16 bytes.
    assert_eq!(&model.arch_tag[..6], b"qwen35");
    assert_eq!(model.feature_flags, 0);
    assert_eq!(model.num_layers(), 2);
}

#[test]
fn qwen_hybrid_mini_load_rejects_wrong_comm_w() {
    let dir = vectors_dir();
    let mut wrong = read_hex_32(&dir.join("comm_w.hex"));
    wrong[0] ^= 1;
    assert!(Model::load(&dir, &wrong).is_err());
}

#[test]
#[ignore = "hybrid forward swapped to GatedDeltaNet semantics; fixture's \
    Mamba-era arithmetic is stale. Regenerate via the NEXT_STEPS.md Path A \
    follow-up (oracle/synthetic_qwen_hybrid_mini.py)."]
fn qwen_hybrid_mini_forward_prefix_byte_equal_to_oracle() {
    let dir = vectors_dir();
    let expected_comm_w = read_hex_32(&dir.join("comm_w.hex"));
    let model = Model::load(&dir, &expected_comm_w).unwrap();

    let prompt = read_u32(&dir.join("prompt.bin"));
    let expected_output = read_i8(&dir.join("forward_layer_2_output.bin"));

    let layout = ActivationLayout {
        seq_len: model.dims.seq_len,
        hidden: model.dims.hidden,
        tile: model.dims.activation_tile,
    };
    let mut log = ActivationLog::new(layout).unwrap();
    let ctx = LayerContext {
        rope_tables: &model.rope_tables,
        softmax_lut: &model.softmax_lut,
        sigmoid_lut: &model.sigmoid_lut,
        ffn_activation: &model.ffn_activation,
    };
    let actual_output =
        forward_prefix(&model, &prompt, 2, &ctx, &mut log).expect("forward_prefix failed");

    assert_eq!(
        actual_output, expected_output,
        "Rust forward output does not match numpy reference (qwen35 hybrid)"
    );

    // Per-layer activation root parity (same pattern as qwen_mini test).
    for layer_idx in 0..=2 {
        let path = dir.join(format!("activation_layer_{layer_idx}.bin"));
        let want = read_i8(&path);
        let mut sanity_log = ActivationLog::new(layout).unwrap();
        sanity_log.record_layer(0, &want).unwrap();
        let oracle_root = sanity_log.root(0).unwrap();
        let rust_root = log.root(layer_idx).unwrap();
        assert_eq!(
            rust_root, oracle_root,
            "activation root divergence at layer {layer_idx}"
        );
    }
}

#[test]
#[ignore = "hybrid layout swapped to DeltaNet semantics; fixture uses stale Mamba dims. \
    Regenerate via NEXT_STEPS.md Path A."]
fn qwen_hybrid_mini_dims_match_meta_txt() {
    let dir = vectors_dir();
    let expected = read_hex_32(&dir.join("comm_w.hex"));
    let model = Model::load(&dir, &expected).unwrap();
    let meta = std::fs::read_to_string(dir.join("meta.txt")).unwrap();
    let mut got_vocab = None;
    let mut got_hidden = None;
    let mut got_seq_len = None;
    let mut got_num_layers = None;
    for kv in meta.split_whitespace() {
        if let Some((k, v)) = kv.split_once('=') {
            match k {
                "vocab" => got_vocab = Some(v.parse::<u32>().unwrap()),
                "hidden" => got_hidden = Some(v.parse::<u32>().unwrap()),
                "seq_len" => got_seq_len = Some(v.parse::<u32>().unwrap()),
                "num_layers" => got_num_layers = Some(v.parse::<u32>().unwrap()),
                _ => {}
            }
        }
    }
    assert_eq!(model.dims.vocab, got_vocab.unwrap());
    assert_eq!(model.dims.hidden, got_hidden.unwrap());
    assert_eq!(model.dims.seq_len, got_seq_len.unwrap());
    assert_eq!(model.num_layers(), got_num_layers.unwrap());
}
