//! Oracle-driven cross-implementation determinism tests.
//!
//! Loads the binary fixtures in `oracle/test_vectors/` (generated by
//! `oracle/synthetic_fixture.py`) and verifies that running the same
//! inputs through the Rust ops produces byte-identical outputs.
//!
//! Two failure modes:
//! 1. The Rust impl drifted: fix the Rust side, then regenerate
//!    fixtures via `python oracle/synthetic_fixture.py`.
//! 2. The numpy reference drifted: fix `oracle/reference_ops.py`,
//!    regenerate fixtures, and verify the new bytes still match.
//!
//! Both directions catch divergence loud — the spec is the agreement of
//! *both* implementations on the same canonical inputs.
//!
//! `cargo test -p ai-pow-vi --test oracle_op_vectors`

use std::path::{Path, PathBuf};

use ai_pow_vi::activation_lut::{ActivationKind, ActivationLut};
use ai_pow_vi::ffn::{ffn_forward, FfnScales, FfnWeights};
use ai_pow_vi::layernorm::layernorm;
use ai_pow_vi::matmul_int8::matmul_int8;
use ai_pow_vi::prompt::synth_prompt;
use ai_pow_vi::quant::{rescale_and_requantize, Scale, SCALE_DENOM_LOG2};
use ai_pow_vi::rmsnorm::{rmsnorm, DEFAULT_EPS_Q};
use ai_pow_vi::softmax::{softmax_int, ExpLut};

fn vectors_dir() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .join("oracle")
        .join("test_vectors")
}

fn read_i8(path: &Path) -> Vec<i8> {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    bytes.into_iter().map(|b| b as i8).collect()
}

fn read_i32(path: &Path) -> Vec<i32> {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    assert_eq!(bytes.len() % 4, 0, "i32 file len must be multiple of 4");
    bytes
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn read_meta(path: &Path) -> std::collections::HashMap<String, String> {
    let s =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut m = std::collections::HashMap::new();
    for kv in s.trim().split_whitespace() {
        if let Some((k, v)) = kv.split_once('=') {
            m.insert(k.to_string(), v.to_string());
        }
    }
    m
}

fn meta_u32(m: &std::collections::HashMap<String, String>, k: &str) -> u32 {
    m.get(k)
        .unwrap_or_else(|| panic!("missing meta key {k}"))
        .parse()
        .unwrap_or_else(|e| panic!("meta {k} not u32: {e}"))
}

fn meta_i32(m: &std::collections::HashMap<String, String>, k: &str) -> i32 {
    m.get(k)
        .unwrap_or_else(|| panic!("missing meta key {k}"))
        .parse()
        .unwrap_or_else(|e| panic!("meta {k} not i32: {e}"))
}

fn meta_i64(m: &std::collections::HashMap<String, String>, k: &str) -> i64 {
    m.get(k)
        .unwrap_or_else(|| panic!("missing meta key {k}"))
        .parse()
        .unwrap_or_else(|e| panic!("meta {k} not i64: {e}"))
}

#[test]
fn oracle_rescale_sweep_matches() {
    let dir = vectors_dir().join("rescale_sweep");
    let meta = read_meta(&dir.join("meta.txt"));
    let len = meta_u32(&meta, "len") as usize;
    let scale_num = meta_i32(&meta, "scale_num");
    let scale = Scale::from_num(scale_num).unwrap();

    let inputs = read_i32(&dir.join("input.bin"));
    let expected = read_i8(&dir.join("output.bin"));
    assert_eq!(inputs.len(), len);
    assert_eq!(expected.len(), len);

    let actual: Vec<i8> = inputs
        .iter()
        .map(|&v| rescale_and_requantize(v, scale))
        .collect();
    assert_eq!(
        actual, expected,
        "rescale_and_requantize divergence vs oracle"
    );
}

#[test]
fn oracle_matmul_canonical_matches() {
    let dir = vectors_dir().join("matmul_canonical");
    let meta = read_meta(&dir.join("meta.txt"));
    let m = meta_u32(&meta, "m");
    let k = meta_u32(&meta, "k");
    let n = meta_u32(&meta, "n");

    let a = read_i8(&dir.join("a.bin"));
    let b = read_i8(&dir.join("b.bin"));
    let expected = read_i32(&dir.join("output.bin"));
    let mut actual = vec![0i32; (m * n) as usize];
    matmul_int8(&a, &b, m, k, n, &mut actual).unwrap();
    assert_eq!(actual, expected, "matmul_int8 divergence vs oracle");
}

#[test]
fn oracle_rmsnorm_canonical_matches() {
    let dir = vectors_dir().join("rmsnorm_canonical");
    let meta = read_meta(&dir.join("meta.txt"));
    let hidden = meta_u32(&meta, "hidden") as usize;
    let eps_q = meta_i64(&meta, "eps_q");
    assert_eq!(eps_q, DEFAULT_EPS_Q);

    let input = read_i8(&dir.join("input.bin"));
    let gamma = read_i8(&dir.join("gamma.bin"));
    let expected = read_i32(&dir.join("output.bin"));
    let mut actual = vec![0i32; hidden];
    rmsnorm(&input, &gamma, &mut actual, eps_q).unwrap();
    assert_eq!(actual, expected, "rmsnorm divergence vs oracle");
}

#[test]
fn oracle_layernorm_canonical_matches() {
    let dir = vectors_dir().join("layernorm_canonical");
    let meta = read_meta(&dir.join("meta.txt"));
    let hidden = meta_u32(&meta, "hidden") as usize;
    let eps_q = meta_i64(&meta, "eps_q");

    let input = read_i8(&dir.join("input.bin"));
    let gamma = read_i8(&dir.join("gamma.bin"));
    let beta = read_i8(&dir.join("beta.bin"));
    let expected = read_i32(&dir.join("output.bin"));
    let mut actual = vec![0i32; hidden];
    layernorm(&input, &gamma, &beta, &mut actual, eps_q).unwrap();
    assert_eq!(actual, expected, "layernorm divergence vs oracle");
}

#[test]
fn oracle_softmax_canonical_matches() {
    let dir = vectors_dir().join("softmax_canonical");

    let scores = read_i32(&dir.join("scores.bin"));
    // Read the i32 LUT (256 * 4 bytes).
    let lut_bytes = std::fs::read(dir.join("lut.bin")).unwrap();
    assert_eq!(lut_bytes.len(), 256 * 4);
    let mut table = [0i32; 256];
    for (i, slot) in table.iter_mut().enumerate() {
        let off = i * 4;
        *slot = i32::from_le_bytes([
            lut_bytes[off],
            lut_bytes[off + 1],
            lut_bytes[off + 2],
            lut_bytes[off + 3],
        ]);
    }
    let lut = ExpLut { table };
    let expected = read_i8(&dir.join("output.bin"));
    let mut actual = vec![0i8; scores.len()];
    softmax_int(&scores, &lut, &mut actual).unwrap();
    assert_eq!(actual, expected, "softmax_int divergence vs oracle");
}

#[test]
fn oracle_ffn_canonical_matches() {
    let dir = vectors_dir().join("ffn_canonical");
    let meta = read_meta(&dir.join("meta.txt"));
    let m = meta_u32(&meta, "m");
    let hidden = meta_u32(&meta, "hidden");
    let intermediate = meta_u32(&meta, "intermediate");
    let gate_num = meta_i32(&meta, "gate_scale");
    let up_num = meta_i32(&meta, "up_scale");
    let mid_num = meta_i32(&meta, "mid_scale");
    let down_num = meta_i32(&meta, "down_scale");

    let input = read_i8(&dir.join("input.bin"));
    let w_gate = read_i8(&dir.join("w_gate.bin"));
    let w_up = read_i8(&dir.join("w_up.bin"));
    let w_down = read_i8(&dir.join("w_down.bin"));
    let expected = read_i8(&dir.join("output.bin"));

    let weights = FfnWeights {
        hidden,
        intermediate,
        w_gate,
        w_up,
        w_down,
    };
    let scales = FfnScales {
        gate: Scale::from_num(gate_num).unwrap(),
        up: Scale::from_num(up_num).unwrap(),
        mid: Scale::from_num(mid_num).unwrap(),
        down: Scale::from_num(down_num).unwrap(),
    };
    // Identity LUT: byte b → i8 (b - 128). Same shape the Python oracle wrote.
    let activation = ActivationLut::identity();
    let _ = ActivationKind::Identity; // touch to silence unused-import worry across edits

    // Sanity: the oracle's identity LUT matches Rust's.
    assert_eq!(
        activation.kind,
        ActivationKind::Identity,
        "expected identity LUT",
    );

    let mut actual = vec![0i8; (m * hidden) as usize];
    ffn_forward(&input, &weights, &activation, scales, m, &mut actual).unwrap();
    assert_eq!(actual, expected, "ffn_forward divergence vs oracle");

    // Cross-check that SCALE_DENOM_LOG2 matches what the oracle used.
    assert_eq!(SCALE_DENOM_LOG2, 15, "scale denom drift");
}

#[test]
fn oracle_synth_prompt_canonical_matches() {
    let dir = vectors_dir().join("synth_prompt_canonical");
    let meta = read_meta(&dir.join("meta.txt"));
    let seq_len = meta_u32(&meta, "seq_len");
    let vocab = meta_u32(&meta, "vocab");

    let block = std::fs::read(dir.join("block.bin")).unwrap();
    let model_id_bytes = std::fs::read(dir.join("model_id.bin")).unwrap();
    assert_eq!(model_id_bytes.len(), 32);
    let mut model_id = [0u8; 32];
    model_id.copy_from_slice(&model_id_bytes);
    let reserved_bytes = std::fs::read(dir.join("reserved.bin")).unwrap();
    let reserved: Vec<u32> = reserved_bytes
        .chunks_exact(4)
        .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    let token_bytes = std::fs::read(dir.join("tokens.bin")).unwrap();
    let expected: Vec<u32> = token_bytes
        .chunks_exact(4)
        .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    assert_eq!(expected.len(), seq_len as usize);

    let actual = synth_prompt(&block, &model_id, seq_len, vocab, &reserved).unwrap();
    assert_eq!(actual, expected, "synth_prompt divergence vs oracle");
}
